### ISSUE TITLE
Crash after IndieGala library import 

### ISSUE THREAD

**Issue by Lacro59** [Lacro59/playnite-indiegala-plugin#7]
Playnite crashed after I Imported my indiegala games.

**Comment by ohadschn** [comment]
Error section from the log:
```
16-10 16:01:49.890|DEBUG|MetadataDownloader:Downloading metadata for Camp Sunshine, 3507337, f7da6eb0-17d7-497c-92fd-347050914954
16-10 16:01:50.056|ERROR|PlayniteApplication:Unhandled exception occured.System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.
   at CefSharp.OffScreen.BitmapBuffer.ResizeBuffer(Int32 width, Int32 height) in C:\projects\cefsharp\CefSharp.OffScreen\BitmapBuffer.cs:line 69
   at CefSharp.OffScreen.BitmapBuffer.UpdateBuffer(Int32 width, Int32 height, IntPtr buffer, Rect dirtyRect) in C:\projects\cefsharp\CefSharp.OffScreen\BitmapBuffer.cs:line 91
   at CefSharp.OffScreen.DefaultRenderHandler.OnPaint(PaintElementType type, Rect dirtyRect, IntPtr buffer, Int32 width, Int32 height) in C:\projects\cefsharp\CefSharp.OffScreen\DefaultRenderHandler.cs:line 161
   at CefSharp.OffScreen.ChromiumWebBrowser.CefSharp.Internals.IRenderWebBrowser.OnPaint(PaintElementType type, Rect dirtyRect, IntPtr buffer, Int32 width, Int32 height) in C:\projects\cefsharp\CefSharp.OffScreen\ChromiumWebBrowser.cs:line 730
   at CefSharp.Internals.RenderClientAdapter.OnPaint(RenderClientAdapter* , scoped_refptr<CefBrowser>* browser, cef_paint_element_type_t type, vector<CefRect\,std::allocator<CefRect> >* dirtyRects, Void* buffer, Int32 width, Int32 height) in c:\projects\cefsharp\cefsharp.core\internals\renderclientadapter.h:line 161
16-10 16:03:38.224|ERROR|Diagnostic:Failed to package extensions list.System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\ohad\AppData\Roaming\Playnite\Themes'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetDirectories(String path)
   at Playnite.Diagnostic.GetManifestInfo(String rootDir, String manFileName) in E:\Devel\Playnite\source\Playnite\Diagnostic.cs:line 46
   at Playnite.Diagnostic.CreateDiagPackage(String path, String userActionsDescription, DiagnosticPackageInfo packageInfo) in E:\Devel\Playnite\source\Playnite\Diagnostic.cs:line 102
```

**Comment by Lacro59** [comment]
This issue is resolved with the next release.
You must wait. Sorry for the inconvenience while waiting.
